# permissions for end users to edit resourcelockers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcelocker-editor-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - resourcelockers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - resourcelockers/status
  verbs:
  - get
