# permissions for end users to view resourcelockers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: resourcelocker-viewer-role
rules:
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - resourcelockers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redhatcop.redhat.io
  resources:
  - resourcelockers/status
  verbs:
  - get
