apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-locker-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: resource-locker-operator
  template:
    metadata:
      labels:
        name: resource-locker-operator
    spec:
      serviceAccountName: resource-locker-operator
      containers:
        - name: resource-locker-operator
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.image.existingPullSecret }}
          imagePullSecrets:
            - name: {{ . }}
          {{- end }}
          command:
          - resource-locker-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "resource-locker-operator"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace              
